
  name: vuerd
  version: '1.0.0'
  summary: ERD
  description: |
    Very Simple ERD

  grade: stable
  confinement: classic

  architectures:
    - build-on: amd64

  parts:
    gnome:
      plugin: nil
      build-packages:
        - software-properties-common
      override-pull: |
        add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
        apt -y update
        apt -y upgrade
    vuerd:
      after:
        - gnome
      plugin: dump
      source: https://github.com/vuerd/vuerd-electron/releases/download/v1.0.0/vuerd.1.0.0.amd64.deb
      source-type: deb
      stage-packages:
        - fcitx-frontend-gtk3
        - libappindicator3-1
        - libasound2
        - libcurl3-gnutls
        - libgconf-2-4
        - libgtk-3-0
        - libnotify4
        - libnspr4
        - libnss3
        - libpcre3
        - libpulse0
        - libxss1
        - libxtst6
    launcher:
      plugin: dump
      source: files/
      prepare: |
        chmod +x bin/launcher
  apps:
    vuerd:
      command: bin/launcher ${SNAP}/usr/share/vuerd/vuerd
      desktop: usr/share/applications/vuerd.desktop
