
  name: vuerd
  version: '1.0.0'
  summary: ERD
  description: |
    Very Simple ERD

  grade: stable
  confinement: classic

  architectures:
    - build-on: amd64

  parts:
    vuerd:
      plugin: dump
      source: https://github.com/vuerd/vuerd-electron/releases/download/v1.0.0/vuerd.1.0.0.amd64.deb
      source-type: deb
      after:
        - desktop-gtk3
      stage-packages:
        - libasound2
        - libgconf2-4
        - libnotify4
        - libnspr4
        - libnss3
        - libpcre3
        - libpulse0
        - libxss1
        - libxtst6
    launcher:
      plugin: dump
      source: files/
      prepare: |
        chmod +x bin/launcher
  apps:
    vuerd:
      command: bin/launcher ${SNAP}/usr/share/vuerd/vuerd
      desktop: usr/share/applications/vuerd.desktop
      environment:
        TMPDIR: $XDG_RUNTIME_DIR
