
  name: vuerd
  version: '1.0.0'
  summary: ERD
  description: |
    Very Simple ERD

  grade: stable
  confinement: classic

  apps:
    vuerd:
      command: desktop-launch $SNAP/vuerd.wrapper

  parts:
    src:
      plugin: nodejs
      node-packages:
        - electron
      source: git://github.com/vuerd/vuerd-electron

    deps:
      plugin: nil
      stage-packages:
        - libgconf-2-4
        - libnss3
        - libxss1
        - fontconfig-config

    desktop-integration:
      plugin: nil
      stage-packages:
        - libappindicator1
        - libdbusmenu-glib4
        - libnotify4
        - libunity9

    launcher:
      plugin: copy
      files:
        vuerd: vuerd.wrapper
      after: [desktop-glib-only]
